export default [
  {
    name: {
      common: 'Barbados',
      official: 'Barbados',
      nativeName: { eng: { official: 'Barbados', common: 'Barbados' } },
    },
    tld: ['.bb'],
    cca2: 'BB',
    ccn3: '052',
    cca3: 'BRB',
    cioc: 'BAR',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { BBD: { name: 'Barbadian dollar', symbol: '$' } },
    idd: { root: '+1', suffixes: ['246'] },
    capital: ['Bridgetown'],
    altSpellings: ['BB'],
    region: 'Americas',
    subregion: 'Caribbean',
    languages: { eng: 'English' },
    translations: {
      ara: { official: 'باربادوس', common: 'باربادوس' },
      bre: { official: 'Barbados', common: 'Barbados' },
      ces: { official: 'Barbados', common: 'Barbados' },
      cym: { official: 'Barbados', common: 'Barbados' },
      deu: { official: 'Barbados', common: 'Barbados' },
      est: { official: 'Barbados', common: 'Barbados' },
      fin: { official: 'Barbados', common: 'Barbados' },
      fra: { official: 'Barbade', common: 'Barbade' },
      hrv: { official: 'Barbados', common: 'Barbados' },
      hun: { official: 'Barbados', common: 'Barbados' },
      ita: { official: 'Barbados', common: 'Barbados' },
      jpn: { official: 'バルバドス', common: 'バルバドス' },
      kor: { official: '바베이도스', common: '바베이도스' },
      nld: { official: 'Barbados', common: 'Barbados' },
      per: { official: 'باربادوس', common: 'باربادوس' },
      pol: { official: 'Barbados', common: 'Barbados' },
      por: { official: 'Barbados', common: 'Barbados' },
      rus: { official: 'Барбадос', common: 'Барбадос' },
      slk: { official: 'Barbados', common: 'Barbados' },
      spa: { official: 'Barbados', common: 'Barbados' },
      srp: { official: 'Барбадос', common: 'Барбадос' },
      swe: { official: 'Barbados', common: 'Barbados' },
      tur: { official: 'Barbados', common: 'Barbados' },
      urd: { official: 'بارباڈوس', common: 'بارباڈوس' },
      zho: { official: '巴巴多斯', common: '巴巴多斯' },
    },
    latlng: [13.16666666, -59.53333333],
    landlocked: false,
    area: 430.0,
    demonyms: {
      eng: { f: 'Barbadian', m: 'Barbadian' },
      fra: { f: 'Barbadienne', m: 'Barbadien' },
    },
    flag: '\uD83C\uDDE7\uD83C\uDDE7',
    maps: {
      googleMaps: 'https://goo.gl/maps/2m36v8STvbGAWd9c7',
      openStreetMaps: 'https://www.openstreetmap.org/relation/547511',
    },
    population: 287371,
    fifa: 'BRB',
    car: { signs: ['BDS'], side: 'left' },
    timezones: ['UTC-04:00'],
    continents: ['North America'],
    flags: {
      png: 'https://flagcdn.com/w320/bb.png',
      svg: 'https://flagcdn.com/bb.svg',
      alt: 'The flag of Barbados is composed of three equal vertical bands of ultramarine, gold and ultramarine. The head of a black trident is centered in the gold band.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/bb.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/bb.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [13.1, -59.62] },
    postalCode: { format: 'BB#####', regex: '^(?:BB)*(\\d{5})$' },
  },
  {
    name: {
      common: 'Réunion',
      official: 'Réunion Island',
      nativeName: {
        fra: { official: 'Ile de la Réunion', common: 'La Réunion' },
      },
    },
    tld: ['.re'],
    cca2: 'RE',
    ccn3: '638',
    cca3: 'REU',
    independent: false,
    status: 'officially-assigned',
    unMember: false,
    currencies: { EUR: { name: 'Euro', symbol: '€' } },
    idd: { root: '+2', suffixes: ['62'] },
    capital: ['Saint-Denis'],
    altSpellings: ['RE', 'Reunion'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    languages: { fra: 'French' },
    translations: {
      ara: { official: 'جزيرة لا ريونيون', common: 'لا ريونيون' },
      bre: { official: 'Enez ar Reünion', common: 'Reünion' },
      ces: { official: 'Réunion', common: 'Réunion' },
      cym: { official: 'Réunion Island', common: 'Réunion' },
      deu: { official: 'Réunion', common: 'Réunion' },
      est: { official: 'Réunioni departemang', common: 'Réunion' },
      fin: { official: 'Réunion', common: 'Réunion' },
      fra: { official: 'Ile de la Réunion', common: 'Réunion' },
      hrv: { official: 'Réunion Island', common: 'Réunion' },
      hun: { official: 'Réunion', common: 'Réunion' },
      ita: { official: 'Réunion', common: 'Riunione' },
      jpn: { official: 'レユニオン島', common: 'レユニオン' },
      kor: { official: '레위니옹', common: '레위니옹' },
      nld: { official: 'Réunion', common: 'Réunion' },
      per: { official: 'رئونیون', common: 'رئونیون' },
      pol: { official: 'Reunion', common: 'Reunion' },
      por: { official: 'Ilha da Reunião', common: 'Reunião' },
      rus: { official: 'Реюньон', common: 'Реюньон' },
      slk: { official: 'Réunionský zámorský departmán', common: 'Réunion' },
      spa: { official: 'Isla de la Reunión', common: 'Reunión' },
      srp: { official: 'Реинион', common: 'Реинион' },
      swe: { official: 'Réunion', common: 'Réunion' },
      tur: { official: 'Réunion', common: 'Réunion' },
      urd: { official: 'رے یونیوں جزیرہ', common: 'رے یونیوں' },
      zho: { official: '留尼旺岛', common: '留尼旺岛' },
    },
    latlng: [-21.15, 55.5],
    landlocked: false,
    area: 2511.0,
    demonyms: {
      eng: { f: 'Réunionese', m: 'Réunionese' },
      fra: { f: 'Réunionnaise', m: 'Réunionnais' },
    },
    flag: '\uD83C\uDDF7\uD83C\uDDEA',
    maps: {
      googleMaps: 'https://goo.gl/maps/wWpBrXsp8UHVbah29',
      openStreetMaps: 'https://www.openstreetmap.org/relation/1785276',
    },
    population: 840974,
    car: { signs: ['F'], side: 'right' },
    timezones: ['UTC+04:00'],
    continents: ['Africa'],
    flags: {
      png: 'https://flagcdn.com/w320/re.png',
      svg: 'https://flagcdn.com/re.svg',
    },
    coatOfArms: {},
    startOfWeek: 'monday',
    capitalInfo: { latlng: [-20.88, 55.45] },
    postalCode: { format: '#####', regex: '^((97|98)(4|7|8)\\d{2})$' },
  },
  {
    name: {
      common: 'Suriname',
      official: 'Republic of Suriname',
      nativeName: {
        nld: { official: 'Republiek Suriname', common: 'Suriname' },
      },
    },
    tld: ['.sr'],
    cca2: 'SR',
    ccn3: '740',
    cca3: 'SUR',
    cioc: 'SUR',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { SRD: { name: 'Surinamese dollar', symbol: '$' } },
    idd: { root: '+5', suffixes: ['97'] },
    capital: ['Paramaribo'],
    altSpellings: [
      'SR',
      'Sarnam',
      'Sranangron',
      'Republic of Suriname',
      'Republiek Suriname',
    ],
    region: 'Americas',
    subregion: 'South America',
    languages: { nld: 'Dutch' },
    translations: {
      ara: { official: 'جمهورية سورينام', common: 'سورينام' },
      bre: { official: 'Republik Surinam', common: 'Surinam' },
      ces: { official: 'Republika Surinam', common: 'Surinam' },
      cym: { official: 'Republic of Suriname', common: 'Suriname' },
      deu: { official: 'Republik Suriname', common: 'Suriname' },
      est: { official: 'Suriname Vabariik', common: 'Suriname' },
      fin: { official: 'Surinamen tasavalta', common: 'Suriname' },
      fra: { official: 'République du Suriname', common: 'Surinam' },
      hrv: { official: 'Republika Surinam', common: 'Surinam' },
      hun: { official: 'Suriname Köztársaság', common: 'Suriname' },
      ita: { official: 'Repubblica del Suriname', common: 'Suriname' },
      jpn: { official: 'スリナム共和国', common: 'スリナム' },
      kor: { official: '수리남 공화국', common: '수리남' },
      nld: { official: 'Republiek Suriname', common: 'Suriname' },
      per: { official: 'جمهوری سورینام', common: 'سورینام' },
      pol: { official: 'Republika Surinamu', common: 'Surinam' },
      por: { official: 'República do Suriname', common: 'Suriname' },
      rus: { official: 'Республика Суринам', common: 'Суринам' },
      slk: { official: 'Surinamská republika', common: 'Surinam' },
      spa: { official: 'República de Suriname', common: 'Surinam' },
      srp: { official: 'Република Суринам', common: 'Суринам' },
      swe: { official: 'Republiken Surinam', common: 'Surinam' },
      tur: { official: 'Surinam Cumhuriyeti', common: 'Surinam' },
      urd: { official: 'جمہوریہ سرینام', common: 'سرینام' },
      zho: { official: '苏里南共和国', common: '苏里南' },
    },
    latlng: [4.0, -56.0],
    landlocked: false,
    borders: ['BRA', 'GUF', 'GUY'],
    area: 163820.0,
    demonyms: {
      eng: { f: 'Surinamer', m: 'Surinamer' },
      fra: { f: 'Surinamaise', m: 'Surinamais' },
    },
    flag: '\uD83C\uDDF8\uD83C\uDDF7',
    maps: {
      googleMaps: 'https://goo.gl/maps/iy7TuQLSi4qgoBoG7',
      openStreetMaps: 'https://www.openstreetmap.org/relation/287082',
    },
    population: 586634,
    gini: { 1999: 57.9 },
    fifa: 'SUR',
    car: { signs: ['SME'], side: 'left' },
    timezones: ['UTC-03:00'],
    continents: ['South America'],
    flags: {
      png: 'https://flagcdn.com/w320/sr.png',
      svg: 'https://flagcdn.com/sr.svg',
      alt: 'The flag of Suriname is composed of five horizontal bands of green, white, red, white and green in the ratio of 2:1:4:1:2. A large five-pointed yellow star is centered in the red band.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/sr.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/sr.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [5.83, -55.17] },
  },
  {
    name: {
      common: 'Namibia',
      official: 'Republic of Namibia',
      nativeName: {
        afr: { official: 'Republiek van Namibië', common: 'Namibië' },
        deu: { official: 'Republik Namibia', common: 'Namibia' },
        eng: { official: 'Republic of Namibia', common: 'Namibia' },
        her: { official: 'Republic of Namibia', common: 'Namibia' },
        hgm: { official: 'Republic of Namibia', common: 'Namibia' },
        kwn: { official: 'Republic of Namibia', common: 'Namibia' },
        loz: { official: 'Republic of Namibia', common: 'Namibia' },
        ndo: { official: 'Republic of Namibia', common: 'Namibia' },
        tsn: { official: 'Lefatshe la Namibia', common: 'Namibia' },
      },
    },
    tld: ['.na'],
    cca2: 'NA',
    ccn3: '516',
    cca3: 'NAM',
    cioc: 'NAM',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: {
      NAD: { name: 'Namibian dollar', symbol: '$' },
      ZAR: { name: 'South African rand', symbol: 'R' },
    },
    idd: { root: '+2', suffixes: ['64'] },
    capital: ['Windhoek'],
    altSpellings: ['NA', 'Namibië', 'Republic of Namibia'],
    region: 'Africa',
    subregion: 'Southern Africa',
    languages: {
      afr: 'Afrikaans',
      deu: 'German',
      eng: 'English',
      her: 'Herero',
      hgm: 'Khoekhoe',
      kwn: 'Kwangali',
      loz: 'Lozi',
      ndo: 'Ndonga',
      tsn: 'Tswana',
    },
    translations: {
      ara: { official: 'جمهورية ناميبيا', common: 'ناميبيا' },
      bre: { official: 'Republik Namibia', common: 'Namibia' },
      ces: { official: 'Namibijská republika', common: 'Namibie' },
      cym: { official: 'Republic of Namibia', common: 'Namibia' },
      deu: { official: 'Republik Namibia', common: 'Namibia' },
      est: { official: 'Namiibia Vabariik', common: 'Namiibia' },
      fin: { official: 'Namibian tasavalta', common: 'Namibia' },
      fra: { official: 'République de Namibie', common: 'Namibie' },
      hrv: { official: 'Republika Namibija', common: 'Namibija' },
      hun: { official: 'Namíbiai Köztársaság', common: 'Namíbia' },
      ita: { official: 'Repubblica di Namibia', common: 'Namibia' },
      jpn: { official: 'ナミビア共和国', common: 'ナミビア' },
      kor: { official: '나미비아 공화국', common: '나미비아' },
      nld: { official: 'Republiek Namibië', common: 'Namibië' },
      per: { official: 'جمهوری نامیبیا', common: 'نامیبیا' },
      pol: { official: 'Republika Namibii', common: 'Namibia' },
      por: { official: 'República da Namíbia', common: 'Namíbia' },
      rus: { official: 'Республика Намибия', common: 'Намибия' },
      slk: { official: 'Namíbijská republika', common: 'Namíbia' },
      spa: { official: 'República de Namibia', common: 'Namibia' },
      srp: { official: 'Република Намибија', common: 'Намибија' },
      swe: { official: 'Republiken Namibia', common: 'Namibia' },
      tur: { official: 'Namibya Cumhuriyeti', common: 'Namibya' },
      urd: { official: 'جمہوریہ نمیبیا', common: 'نمیبیا' },
      zho: { official: '纳米比亚共和国', common: '纳米比亚' },
    },
    latlng: [-22.0, 17.0],
    landlocked: false,
    borders: ['AGO', 'BWA', 'ZAF', 'ZMB'],
    area: 825615.0,
    demonyms: {
      eng: { f: 'Namibian', m: 'Namibian' },
      fra: { f: 'Namibienne', m: 'Namibien' },
    },
    flag: '\uD83C\uDDF3\uD83C\uDDE6',
    maps: {
      googleMaps: 'https://goo.gl/maps/oR1i8BFEYX3EY83WA',
      openStreetMaps: 'https://www.openstreetmap.org/relation/195266',
    },
    population: 2540916,
    gini: { 2015: 59.1 },
    fifa: 'NAM',
    car: { signs: ['NAM'], side: 'left' },
    timezones: ['UTC+01:00'],
    continents: ['Africa'],
    flags: {
      png: 'https://flagcdn.com/w320/na.png',
      svg: 'https://flagcdn.com/na.svg',
      alt: 'The flag of Namibia features a white-edged red diagonal band that extends from the lower hoist-side corner to the upper fly-side corner of the field. Above and beneath this band are a blue and green triangle respectively. A gold sun with twelve triangular rays is situated on the hoist side of the upper triangle.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/na.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/na.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [-22.57, 17.08] },
  },
  {
    name: {
      common: 'Guinea',
      official: 'Republic of Guinea',
      nativeName: {
        fra: { official: 'République de Guinée', common: 'Guinée' },
      },
    },
    tld: ['.gn'],
    cca2: 'GN',
    ccn3: '324',
    cca3: 'GIN',
    cioc: 'GUI',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { GNF: { name: 'Guinean franc', symbol: 'Fr' } },
    idd: { root: '+2', suffixes: ['24'] },
    capital: ['Conakry'],
    altSpellings: ['GN', 'Republic of Guinea', 'République de Guinée'],
    region: 'Africa',
    subregion: 'Western Africa',
    languages: { fra: 'French' },
    translations: {
      ara: { official: 'جمهورية غينيا', common: 'غينيا' },
      bre: { official: 'Republik Ginea', common: 'Ginea' },
      ces: { official: 'Guinejská republika', common: 'Guinea' },
      cym: { official: 'Republic of Guinea', common: 'Guinea' },
      deu: { official: 'Republik Guinea', common: 'Guinea' },
      est: { official: 'Guinea Vabariik', common: 'Guinea' },
      fin: { official: 'Guinean tasavalta', common: 'Guinea' },
      fra: { official: 'République de Guinée', common: 'Guinée' },
      hrv: { official: 'Republika Gvineja', common: 'Gvineja' },
      hun: { official: 'Guineai Köztársaság', common: 'Guinea' },
      ita: { official: 'Repubblica di Guinea', common: 'Guinea' },
      jpn: { official: 'ギニア共和国', common: 'ギニア' },
      kor: { official: '기니 공화국', common: '기니' },
      nld: { official: 'Republiek Guinee', common: 'Guinee' },
      per: { official: 'مملکت مستقل پاپوآ گینه نو', common: 'پاپوآ گینه نو' },
      pol: { official: 'Republika Gwinei', common: 'Gwinea' },
      por: { official: 'República da Guiné', common: 'Guiné' },
      rus: { official: 'Республика Гвинея', common: 'Гвинея' },
      slk: { official: 'Guinejská republika', common: 'Guinea' },
      spa: { official: 'República de Guinea', common: 'Guinea' },
      srp: { official: 'Кооперативна Република Гвајана', common: 'Гвајана' },
      swe: { official: 'Republiken Guinea', common: 'Guinea' },
      tur: { official: 'Gine Cumhuriyeti', common: 'Gine' },
      urd: { official: 'جمہوریہ گنی', common: 'گنی' },
      zho: { official: '几内亚共和国', common: '几内亚' },
    },
    latlng: [11.0, -10.0],
    landlocked: false,
    borders: ['CIV', 'GNB', 'LBR', 'MLI', 'SEN', 'SLE'],
    area: 245857.0,
    demonyms: {
      eng: { f: 'Guinean', m: 'Guinean' },
      fra: { f: 'Guinéenne', m: 'Guinéen' },
    },
    flag: '\uD83C\uDDEC\uD83C\uDDF3',
    maps: {
      googleMaps: 'https://goo.gl/maps/8J5oM5sA4Ayr1ZYGA',
      openStreetMaps: 'https://www.openstreetmap.org/relation/192778',
    },
    population: 13132792,
    gini: { 2012: 33.7 },
    fifa: 'GUI',
    car: { signs: ['RG'], side: 'right' },
    timezones: ['UTC'],
    continents: ['Africa'],
    flags: {
      png: 'https://flagcdn.com/w320/gn.png',
      svg: 'https://flagcdn.com/gn.svg',
      alt: 'The flag of Guinea is composed of three equal vertical bands of red, yellow and green.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/gn.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/gn.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [9.5, -13.7] },
  },
  {
    name: {
      common: 'Vanuatu',
      official: 'Republic of Vanuatu',
      nativeName: {
        bis: { official: 'Ripablik blong Vanuatu', common: 'Vanuatu' },
        eng: { official: 'Republic of Vanuatu', common: 'Vanuatu' },
        fra: { official: 'République de Vanuatu', common: 'Vanuatu' },
      },
    },
    tld: ['.vu'],
    cca2: 'VU',
    ccn3: '548',
    cca3: 'VUT',
    cioc: 'VAN',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { VUV: { name: 'Vanuatu vatu', symbol: 'Vt' } },
    idd: { root: '+6', suffixes: ['78'] },
    capital: ['Port Vila'],
    altSpellings: [
      'VU',
      'Republic of Vanuatu',
      'Ripablik blong Vanuatu',
      'République de Vanuatu',
    ],
    region: 'Oceania',
    subregion: 'Melanesia',
    languages: { bis: 'Bislama', eng: 'English', fra: 'French' },
    translations: {
      ara: { official: 'جمهورية فانواتو', common: 'فانواتو' },
      bre: { official: 'Republik Vanuatu', common: 'Vanuatu' },
      ces: { official: 'Republika Vanuatu', common: 'Vanuatu' },
      cym: { official: 'Republic of Vanuatu', common: 'Vanuatu' },
      deu: { official: 'Vanuatu', common: 'Vanuatu' },
      est: { official: 'Vanuatu Vabariik', common: 'Vanuatu' },
      fin: { official: 'Vanuatun tasavalta', common: 'Vanuatu' },
      fra: { official: 'République de Vanuatu', common: 'Vanuatu' },
      hrv: { official: 'Republika Vanuatu', common: 'Vanuatu' },
      hun: { official: 'Vanuatui Köztársaság', common: 'Vanuatu' },
      ita: { official: 'Repubblica di Vanuatu', common: 'Vanuatu' },
      jpn: { official: 'バヌアツ共和国', common: 'バヌアツ' },
      kor: { official: '바누아투 공화국', common: '바누아투' },
      nld: { official: 'Republiek Vanuatu', common: 'Vanuatu' },
      per: { official: 'جمهوری وانواتو', common: 'وانواتو' },
      pol: { official: 'Republika Vanuatu', common: 'Vanuatu' },
      por: { official: 'República de Vanuatu', common: 'Vanuatu' },
      rus: { official: 'Республика Вануату', common: 'Вануату' },
      slk: { official: 'Vanuatská republika', common: 'Vanuatu' },
      spa: { official: 'República de Vanuatu', common: 'Vanuatu' },
      srp: { official: 'Република Вануату', common: 'Вануату' },
      swe: { official: 'Republiken Vanuatu', common: 'Vanuatu' },
      tur: { official: 'Vanuatu Cumhuriyeti', common: 'Vanuatu' },
      urd: { official: 'جمہوریہ وانواتو', common: 'وانواتو' },
      zho: { official: '瓦努阿图共和国', common: '瓦努阿图' },
    },
    latlng: [-16.0, 167.0],
    landlocked: false,
    area: 12189.0,
    demonyms: {
      eng: { f: 'Ni-Vanuatu', m: 'Ni-Vanuatu' },
      fra: { f: 'Vanuatuane', m: 'Vanuatuan' },
    },
    flag: '\uD83C\uDDFB\uD83C\uDDFA',
    maps: {
      googleMaps: 'https://goo.gl/maps/hwAjehcT7VfvP5zJ8',
      openStreetMaps: 'https://www.openstreetmap.org/relation/2177246',
    },
    population: 307150,
    gini: { 2010: 37.6 },
    fifa: 'VAN',
    car: { signs: ['VU'], side: 'right' },
    timezones: ['UTC+11:00'],
    continents: ['Oceania'],
    flags: {
      png: 'https://flagcdn.com/w320/vu.png',
      svg: 'https://flagcdn.com/vu.svg',
      alt: "The flag of Vanuatu is composed of two equal horizontal bands of red and green, with a black isosceles triangle superimposed on the hoist side of the field. This triangle has its base on the hoist end, spans about two-fifth the width of the field and is enclosed on its sides by the arms of a thin black-edged yellow horizontally oriented Y-shaped band which extends along the boundary of the red and green bands to the fly end of the field. A yellow boar's tusk encircling two yellow crossed namele leaves is centered in the triangle.",
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/vu.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/vu.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [-17.73, 168.32] },
  },
  {
    name: {
      common: 'Samoa',
      official: 'Independent State of Samoa',
      nativeName: {
        eng: { official: 'Independent State of Samoa', common: 'Samoa' },
        smo: { official: 'Malo Saʻoloto Tutoʻatasi o Sāmoa', common: 'Sāmoa' },
      },
    },
    tld: ['.ws'],
    cca2: 'WS',
    ccn3: '882',
    cca3: 'WSM',
    cioc: 'SAM',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { WST: { name: 'Samoan tālā', symbol: 'T' } },
    idd: { root: '+6', suffixes: ['85'] },
    capital: ['Apia'],
    altSpellings: [
      'WS',
      'Independent State of Samoa',
      'Malo Saʻoloto Tutoʻatasi o Sāmoa',
    ],
    region: 'Oceania',
    subregion: 'Polynesia',
    languages: { eng: 'English', smo: 'Samoan' },
    translations: {
      ara: { official: 'دولة ساموا المستقلة', common: 'ساموا' },
      bre: { official: "Stad Dizalc'h Samoa", common: 'Samoa' },
      ces: { official: 'Nezávislý stát Samoa', common: 'Samoa' },
      cym: { official: 'Independent State of Samoa', common: 'Samoa' },
      deu: { official: 'Unabhängige Staat Samoa', common: 'Samoa' },
      est: { official: 'Samoa Iseseisvusriik', common: 'Samoa' },
      fin: { official: 'Samoan itsenäinen valtio', common: 'Samoa' },
      fra: { official: 'Samoa', common: 'Samoa' },
      hrv: { official: 'Nezavisna Država Samoa', common: 'Samoa' },
      hun: { official: 'Szamoai Független Állam', common: 'Szamoa' },
      ita: { official: 'Stato indipendente di Samoa', common: 'Samoa' },
      jpn: { official: 'サモア独立国', common: 'サモア' },
      kor: { official: '사모아 독립국', common: '사모아' },
      nld: { official: 'Onafhankelijke Staat Samoa', common: 'Samoa' },
      per: { official: 'ایالت مستقل ساموآ', common: 'ساموآ' },
      pol: { official: 'Niezależne Państwo Samoa', common: 'Samoa' },
      por: { official: 'Estado Independente de Samoa', common: 'Samoa' },
      rus: { official: 'Независимое Государство Самоа', common: 'Самоа' },
      slk: { official: 'Nezávislý štátSamoa', common: 'Samoa' },
      spa: { official: 'Estado Independiente de Samoa', common: 'Samoa' },
      srp: { official: 'Независна Држава Самоа', common: 'Самоа' },
      swe: { official: 'Självständiga staten Samoa', common: 'Samoa' },
      tur: {
        official: 'Bağımsız Samoa Devleti',
        common: 'Bağımsız Samoa Devleti',
      },
      urd: { official: 'آزاد سلطنتِ ساموا', common: 'سامووا' },
      zho: { official: '萨摩亚独立国', common: '萨摩亚' },
    },
    latlng: [-13.58333333, -172.33333333],
    landlocked: false,
    area: 2842.0,
    demonyms: {
      eng: { f: 'Samoan', m: 'Samoan' },
      fra: { f: 'Samoane', m: 'Samoan' },
    },
    flag: '\uD83C\uDDFC\uD83C\uDDF8',
    maps: {
      googleMaps: 'https://goo.gl/maps/CFC9fEFP9cfkYUBF9',
      openStreetMaps: 'https://www.openstreetmap.org/relation/1872673',
    },
    population: 198410,
    gini: { 2013: 38.7 },
    fifa: 'SAM',
    car: { signs: ['WS'], side: 'left' },
    timezones: ['UTC+13:00'],
    continents: ['Oceania'],
    flags: {
      png: 'https://flagcdn.com/w320/ws.png',
      svg: 'https://flagcdn.com/ws.svg',
      alt: 'The flag of Samoa has a red field. A blue rectangle, bearing a representation of the Southern Cross made up of five large and one smaller five-pointed white stars, is superimposed in the canton.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/ws.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/ws.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [-13.82, -171.77] },
  },
  {
    name: {
      common: 'France',
      official: 'French Republic',
      nativeName: {
        fra: { official: 'République française', common: 'France' },
      },
    },
    tld: ['.fr'],
    cca2: 'FR',
    ccn3: '250',
    cca3: 'FRA',
    cioc: 'FRA',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { EUR: { name: 'Euro', symbol: '€' } },
    idd: { root: '+3', suffixes: ['3'] },
    capital: ['Paris'],
    altSpellings: ['FR', 'French Republic', 'République française'],
    region: 'Europe',
    subregion: 'Western Europe',
    languages: { fra: 'French' },
    translations: {
      ara: { official: 'الجمهورية الفرنسية', common: 'فرنسا' },
      bre: { official: 'Republik Frañs', common: 'Frañs' },
      ces: { official: 'Francouzská republika', common: 'Francie' },
      cym: { official: 'French Republic', common: 'France' },
      deu: { official: 'Französische Republik', common: 'Frankreich' },
      est: { official: 'Prantsuse Vabariik', common: 'Prantsusmaa' },
      fin: { official: 'Ranskan tasavalta', common: 'Ranska' },
      fra: { official: 'République française', common: 'France' },
      hrv: { official: 'Francuska Republika', common: 'Francuska' },
      hun: { official: 'Francia Köztársaság', common: 'Franciaország' },
      ita: { official: 'Repubblica francese', common: 'Francia' },
      jpn: { official: 'フランス共和国', common: 'フランス' },
      kor: { official: '프랑스 공화국', common: '프랑스' },
      nld: { official: 'Franse Republiek', common: 'Frankrijk' },
      per: { official: 'جمهوری فرانسه', common: 'فرانسه' },
      pol: { official: 'Republika Francuska', common: 'Francja' },
      por: { official: 'República Francesa', common: 'França' },
      rus: { official: 'Французская Республика', common: 'Франция' },
      slk: { official: 'Francúzska republika', common: 'Francúzsko' },
      spa: { official: 'República francés', common: 'Francia' },
      srp: { official: 'Француска Република', common: 'Француска' },
      swe: { official: 'Republiken Frankrike', common: 'Frankrike' },
      tur: { official: 'Fransa Cumhuriyeti', common: 'Fransa' },
      urd: { official: 'جمہوریہ فرانس', common: 'فرانس' },
      zho: { official: '法兰西共和国', common: '法国' },
    },
    latlng: [46.0, 2.0],
    landlocked: false,
    borders: ['AND', 'BEL', 'DEU', 'ITA', 'LUX', 'MCO', 'ESP', 'CHE'],
    area: 551695.0,
    demonyms: {
      eng: { f: 'French', m: 'French' },
      fra: { f: 'Française', m: 'Français' },
    },
    flag: '\uD83C\uDDEB\uD83C\uDDF7',
    maps: {
      googleMaps: 'https://goo.gl/maps/g7QxxSFsWyTPKuzd7',
      openStreetMaps: 'https://www.openstreetmap.org/relation/1403916',
    },
    population: 67391582,
    gini: { 2018: 32.4 },
    fifa: 'FRA',
    car: { signs: ['F'], side: 'right' },
    timezones: [
      'UTC-10:00',
      'UTC-09:30',
      'UTC-09:00',
      'UTC-08:00',
      'UTC-04:00',
      'UTC-03:00',
      'UTC+01:00',
      'UTC+02:00',
      'UTC+03:00',
      'UTC+04:00',
      'UTC+05:00',
      'UTC+10:00',
      'UTC+11:00',
      'UTC+12:00',
    ],
    continents: ['Europe'],
    flags: {
      png: 'https://flagcdn.com/w320/fr.png',
      svg: 'https://flagcdn.com/fr.svg',
      alt: 'The flag of France is composed of three equal vertical bands of blue, white and red.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/fr.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/fr.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [48.87, 2.33] },
    postalCode: { format: '#####', regex: '^(\\d{5})$' },
  },
  {
    name: {
      common: 'Andorra',
      official: 'Principality of Andorra',
      nativeName: {
        cat: { official: "Principat d'Andorra", common: 'Andorra' },
      },
    },
    tld: ['.ad'],
    cca2: 'AD',
    ccn3: '020',
    cca3: 'AND',
    cioc: 'AND',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { EUR: { name: 'Euro', symbol: '€' } },
    idd: { root: '+3', suffixes: ['76'] },
    capital: ['Andorra la Vella'],
    altSpellings: ['AD', 'Principality of Andorra', "Principat d'Andorra"],
    region: 'Europe',
    subregion: 'Southern Europe',
    languages: { cat: 'Catalan' },
    translations: {
      ara: { official: 'إمارة أندورا', common: 'أندورا' },
      bre: { official: 'Priñselezh Andorra', common: 'Andorra' },
      ces: { official: 'Andorrské knížectví', common: 'Andorra' },
      cym: { official: 'Tywysogaeth Andorra', common: 'Andorra' },
      deu: { official: 'Fürstentum Andorra', common: 'Andorra' },
      est: { official: 'Andorra Vürstiriik', common: 'Andorra' },
      fin: { official: 'Andorran ruhtinaskunta', common: 'Andorra' },
      fra: { official: "Principauté d'Andorre", common: 'Andorre' },
      hrv: { official: 'Kneževina Andora', common: 'Andora' },
      hun: { official: 'Andorra', common: 'Andorra' },
      ita: { official: 'Principato di Andorra', common: 'Andorra' },
      jpn: { official: 'アンドラ公国', common: 'アンドラ' },
      kor: { official: '안도라 공국', common: '안도라' },
      nld: { official: 'Prinsdom Andorra', common: 'Andorra' },
      per: { official: 'شاهزاده‌نشین آندورا', common: 'آندورا' },
      pol: { official: 'Księstwo Andory', common: 'Andora' },
      por: { official: 'Principado de Andorra', common: 'Andorra' },
      rus: { official: 'Княжество Андорра', common: 'Андорра' },
      slk: { official: 'Andorrské kniežatstvo', common: 'Andorra' },
      spa: { official: 'Principado de Andorra', common: 'Andorra' },
      srp: { official: 'Кнежевина Андора', common: 'Андора' },
      swe: { official: 'Furstendömet Andorra', common: 'Andorra' },
      tur: { official: 'Andorra Prensliği', common: 'Andorra' },
      urd: { official: 'اماراتِ انڈورا', common: 'انڈورا' },
      zho: { official: '安道尔公国', common: '安道尔' },
    },
    latlng: [42.5, 1.5],
    landlocked: true,
    borders: ['FRA', 'ESP'],
    area: 468.0,
    demonyms: {
      eng: { f: 'Andorran', m: 'Andorran' },
      fra: { f: 'Andorrane', m: 'Andorran' },
    },
    flag: '\uD83C\uDDE6\uD83C\uDDE9',
    maps: {
      googleMaps: 'https://goo.gl/maps/JqAnacWE2qEznKgw7',
      openStreetMaps: 'https://www.openstreetmap.org/relation/9407',
    },
    population: 77265,
    fifa: 'AND',
    car: { signs: ['AND'], side: 'right' },
    timezones: ['UTC+01:00'],
    continents: ['Europe'],
    flags: {
      png: 'https://flagcdn.com/w320/ad.png',
      svg: 'https://flagcdn.com/ad.svg',
      alt: 'The flag of Andorra features three equal vertical bands of blue, yellow and red, with the coat of arms of Andorra centered in the yellow band.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/ad.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/ad.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [42.5, 1.52] },
    postalCode: { format: 'AD###', regex: '^(?:AD)*(\\d{3})$' },
  },
  {
    name: {
      common: 'Azerbaijan',
      official: 'Republic of Azerbaijan',
      nativeName: {
        aze: { official: 'Azərbaycan Respublikası', common: 'Azərbaycan' },
        rus: { official: 'Азербайджанская Республика', common: 'Азербайджан' },
      },
    },
    tld: ['.az'],
    cca2: 'AZ',
    ccn3: '031',
    cca3: 'AZE',
    cioc: 'AZE',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { AZN: { name: 'Azerbaijani manat', symbol: '₼' } },
    idd: { root: '+9', suffixes: ['94'] },
    capital: ['Baku'],
    altSpellings: ['AZ', 'Republic of Azerbaijan', 'Azərbaycan Respublikası'],
    region: 'Asia',
    subregion: 'Western Asia',
    languages: { aze: 'Azerbaijani', rus: 'Russian' },
    translations: {
      ara: { official: 'جمهورية أذربيجان', common: 'أذربيجان' },
      bre: { official: 'Republik Azerbaidjan', common: 'Azerbaidjan' },
      ces: { official: 'Ázerbájdžánská republika', common: 'Ázerbájdžán' },
      cym: { official: 'Gweriniaeth Aserbaijan', common: 'Aserbaijan' },
      deu: { official: 'Republik Aserbaidschan', common: 'Aserbaidschan' },
      est: { official: 'Aserbaidžaani Vabariik', common: 'Aserbaidžaan' },
      fin: { official: 'Azerbaidzanin tasavalta', common: 'Azerbaidzan' },
      fra: { official: "République d'Azerbaïdjan", common: 'Azerbaïdjan' },
      hrv: { official: 'Republika Azerbajdžan', common: 'Azerbajdžan' },
      hun: { official: 'Azerbajdzsán', common: 'Azerbajdzsán' },
      ita: { official: "Repubblica dell'Azerbaigian", common: 'Azerbaijan' },
      jpn: { official: 'アゼルバイジャン共和国', common: 'アゼルバイジャン' },
      kor: { official: '아제르바이잔 공화국', common: '아제르바이잔' },
      nld: { official: 'Republiek Azerbeidzjan', common: 'Azerbeidzjan' },
      per: { official: 'جمهوری آذربایجان', common: 'جمهوری آذربایجان' },
      pol: { official: 'Republika Azerbejdżanu', common: 'Azerbejdżan' },
      por: { official: 'República do Azerbaijão', common: 'Azerbeijão' },
      rus: { official: 'Азербайджанская Республика', common: 'Азербайджан' },
      slk: { official: 'Azerbajǆanská republika', common: 'AzerbajǇan' },
      spa: { official: 'República de Azerbaiyán', common: 'Azerbaiyán' },
      srp: { official: 'Азербејџанска Република', common: 'Азербејџан' },
      swe: { official: 'Republiken Azerbajdzjan', common: 'Azerbajdzjan' },
      tur: { official: 'Azerbaycan Cumhuriyeti', common: 'Azerbaycan' },
      urd: { official: 'جمہوریہ آذربائیجان', common: 'آذربائیجان' },
      zho: { official: '阿塞拜疆共和国', common: '阿塞拜疆' },
    },
    latlng: [40.5, 47.5],
    landlocked: true,
    borders: ['ARM', 'GEO', 'IRN', 'RUS', 'TUR'],
    area: 86600.0,
    demonyms: {
      eng: { f: 'Azerbaijani', m: 'Azerbaijani' },
      fra: { f: 'Azerbaïdjanaise', m: 'Azerbaïdjanais' },
    },
    flag: '\uD83C\uDDE6\uD83C\uDDFF',
    maps: {
      googleMaps: 'https://goo.gl/maps/az3Zz7ar2aoB9AUc6',
      openStreetMaps: 'https://www.openstreetmap.org/relation/364110',
    },
    population: 10110116,
    gini: { 2005: 26.6 },
    fifa: 'AZE',
    car: { signs: ['AZ'], side: 'right' },
    timezones: ['UTC+04:00'],
    continents: ['Asia'],
    flags: {
      png: 'https://flagcdn.com/w320/az.png',
      svg: 'https://flagcdn.com/az.svg',
      alt: 'The flag of Azerbaijan features three equal horizontal bands of blue, red and green, with a white fly-side facing crescent and eight-pointed star centered in the red band.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/az.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/az.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [40.38, 49.87] },
    postalCode: { format: 'AZ ####', regex: '^(?:AZ)*(\\d{4})$' },
  },
  {
    name: {
      common: 'Maldives',
      official: 'Republic of the Maldives',
      nativeName: {
        div: {
          official: 'ދިވެހިރާއްޖޭގެ ޖުމްހޫރިއްޔާ',
          common: 'ދިވެހިރާއްޖޭގެ',
        },
      },
    },
    tld: ['.mv'],
    cca2: 'MV',
    ccn3: '462',
    cca3: 'MDV',
    cioc: 'MDV',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { MVR: { name: 'Maldivian rufiyaa', symbol: '.ރ' } },
    idd: { root: '+9', suffixes: ['60'] },
    capital: ['Malé'],
    altSpellings: [
      'MV',
      'Maldive Islands',
      'Republic of the Maldives',
      'Dhivehi Raajjeyge Jumhooriyya',
    ],
    region: 'Asia',
    subregion: 'Southern Asia',
    languages: { div: 'Maldivian' },
    translations: {
      ara: { official: 'جمهورية المالديف', common: 'المالديف' },
      bre: { official: 'Republik Maldivez', common: 'Maldivez' },
      ces: { official: 'Maledivská republika', common: 'Maledivy' },
      cym: { official: 'Republic of the Maldives', common: 'Maldives' },
      deu: { official: 'Republik Malediven', common: 'Malediven' },
      est: { official: 'Maldiivi Vabariik', common: 'Maldiivid' },
      fin: { official: 'Malediivien tasavalta', common: 'Malediivit' },
      fra: { official: 'République des Maldives', common: 'Maldives' },
      hrv: { official: 'Republika Maldivi', common: 'Maldivi' },
      hun: { official: 'Maldív-szigetek', common: 'Maldív-szigetek' },
      ita: { official: 'Repubblica delle Maldive', common: 'Maldive' },
      jpn: { official: 'モルディブ共和国', common: 'モルディブ' },
      kor: { official: '몰디브 공화국', common: '몰디브' },
      nld: { official: 'Republiek van de Malediven', common: 'Maldiven' },
      per: { official: 'جمهوری مالدیو', common: 'مالدیو' },
      pol: { official: 'Republika Malediwów', common: 'Malediwy' },
      por: { official: 'República das Maldivas', common: 'Maldivas' },
      rus: { official: 'Республика Мальдивы', common: 'Мальдивы' },
      slk: { official: 'Maldivská republika', common: 'Maldivy' },
      spa: { official: 'República de las Maldivas', common: 'Maldivas' },
      srp: { official: 'Малдивска Република', common: 'Малдиви' },
      swe: { official: 'Republiken Maldiverna', common: 'Maldiverna' },
      tur: { official: 'Maldivler Cumhuriyeti', common: 'Maldivler' },
      urd: { official: 'جمہوریہ مالدیپ', common: 'مالدیپ' },
      zho: { official: '马尔代夫共和国', common: '马尔代夫' },
    },
    latlng: [3.25, 73.0],
    landlocked: false,
    area: 300.0,
    demonyms: {
      eng: { f: 'Maldivan', m: 'Maldivan' },
      fra: { f: 'Maldivienne', m: 'Maldivien' },
    },
    flag: '\uD83C\uDDF2\uD83C\uDDFB',
    maps: {
      googleMaps: 'https://goo.gl/maps/MNAWGq9vEdbZ9vUV7',
      openStreetMaps: 'https://www.openstreetmap.org/relation/536773',
    },
    population: 540542,
    gini: { 2016: 31.3 },
    fifa: 'MDV',
    car: { signs: ['MV'], side: 'left' },
    timezones: ['UTC+05:00'],
    continents: ['Asia'],
    flags: {
      png: 'https://flagcdn.com/w320/mv.png',
      svg: 'https://flagcdn.com/mv.svg',
      alt: 'The flag of Maldives has a red field, at the center of which is a large green rectangle bearing a fly-side facing white crescent.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/mv.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/mv.svg',
    },
    startOfWeek: 'sunday',
    capitalInfo: { latlng: [4.17, 73.51] },
    postalCode: { format: '#####', regex: '^(\\d{5})$' },
  },
  {
    name: {
      common: 'French Polynesia',
      official: 'French Polynesia',
      nativeName: {
        fra: { official: 'Polynésie française', common: 'Polynésie française' },
      },
    },
    tld: ['.pf'],
    cca2: 'PF',
    ccn3: '258',
    cca3: 'PYF',
    independent: false,
    status: 'officially-assigned',
    unMember: false,
    currencies: { XPF: { name: 'CFP franc', symbol: '₣' } },
    idd: { root: '+6', suffixes: ['89'] },
    capital: ['Papeetē'],
    altSpellings: [
      'PF',
      'Polynésie française',
      'French Polynesia',
      'Pōrīnetia Farāni',
    ],
    region: 'Oceania',
    subregion: 'Polynesia',
    languages: { fra: 'French' },
    translations: {
      ara: { official: 'بولينزيا الفرنسية', common: 'بولينزيا الفرنسية' },
      bre: { official: "Polinezia C'hall", common: "Polinezia C'hall" },
      ces: {
        official: 'Francouzská Polynésie',
        common: 'Francouzská Polynésie',
      },
      cym: { official: 'French Polynesia', common: 'French Polynesia' },
      deu: {
        official: 'Französisch-Polynesien',
        common: 'Französisch-Polynesien',
      },
      est: { official: 'Prantsuse Polüneesia', common: 'Prantsuse Polüneesia' },
      fin: { official: 'Ranskan Polynesia', common: 'Ranskan Polynesia' },
      fra: { official: 'Polynésie française', common: 'Polynésie française' },
      hrv: { official: 'Francuska Polinezija', common: 'Francuska Polinezija' },
      hun: { official: 'Francia Polinézia', common: 'Francia Polinézia' },
      ita: { official: 'Polinesia Francese', common: 'Polinesia Francese' },
      jpn: { official: 'フランス領ポリネシア', common: 'フランス領ポリネシア' },
      kor: { official: '프랑스령 폴리네시아', common: '프랑스령 폴리네시아' },
      nld: { official: 'Frans-Polynesië', common: 'Frans-Polynesië' },
      per: { official: 'پُلی‌نِزی فرانسه', common: 'پُلی‌نِزی فرانسه' },
      pol: { official: 'Polinezja Francuska', common: 'Polinezja Francuska' },
      por: { official: 'Polinésia Francesa', common: 'Polinésia Francesa' },
      rus: {
        official: 'Французская Полинезия',
        common: 'Французская Полинезия',
      },
      slk: { official: 'Francúzska Polynézia', common: 'Francúzska Polynézia' },
      spa: { official: 'Polinesia francés', common: 'Polinesia Francesa' },
      srp: { official: 'Француска Полинезија', common: 'Француска Полинезија' },
      swe: { official: 'Franska Polynesien', common: 'Franska Polynesien' },
      tur: { official: 'Fransız Polinezyası', common: 'Fransız Polinezyası' },
      urd: { official: 'فرانسیسی پولینیشیا', common: 'فرانسیسی پولینیشیا' },
      zho: { official: '法属波利尼西亚', common: '法属波利尼西亚' },
    },
    latlng: [17.6797, 149.4068],
    landlocked: false,
    area: 4167.0,
    demonyms: {
      eng: { f: 'French Polynesian', m: 'French Polynesian' },
      fra: { f: 'Polynésienne', m: 'Polynésien' },
    },
    flag: '\uD83C\uDDF5\uD83C\uDDEB',
    maps: {
      googleMaps: 'https://goo.gl/maps/xgg6BQTRyeQg4e1m6',
      openStreetMaps: 'https://www.openstreetmap.org/relation/3412620',
    },
    population: 280904,
    car: { signs: ['F'], side: 'right' },
    timezones: ['UTC-10:00', 'UTC-09:30', 'UTC-09:00'],
    continents: ['Oceania'],
    flags: {
      png: 'https://flagcdn.com/w320/pf.png',
      svg: 'https://flagcdn.com/pf.svg',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/pf.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/pf.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [-17.53, -149.56] },
    postalCode: { format: '#####', regex: '^((97|98)7\\d{2})$' },
  },
  {
    name: {
      common: 'Saint Lucia',
      official: 'Saint Lucia',
      nativeName: { eng: { official: 'Saint Lucia', common: 'Saint Lucia' } },
    },
    tld: ['.lc'],
    cca2: 'LC',
    ccn3: '662',
    cca3: 'LCA',
    cioc: 'LCA',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { XCD: { name: 'Eastern Caribbean dollar', symbol: '$' } },
    idd: { root: '+1', suffixes: ['758'] },
    capital: ['Castries'],
    altSpellings: ['LC'],
    region: 'Americas',
    subregion: 'Caribbean',
    languages: { eng: 'English' },
    translations: {
      ara: { official: 'سانت لوسيا', common: 'سانت لوسيا' },
      bre: { official: 'Santez-Lusia', common: 'Santez-Lusia' },
      ces: { official: 'Svatá Lucie', common: 'Svatá Lucie' },
      cym: { official: 'Saint Lucia', common: 'Saint Lucia' },
      deu: { official: 'St. Lucia', common: 'St. Lucia' },
      est: { official: 'Saint Lucia', common: 'Saint Lucia' },
      fin: { official: 'Saint Lucia', common: 'Saint Lucia' },
      fra: { official: 'Sainte-Lucie', common: 'Sainte-Lucie' },
      hrv: { official: 'Sveta Lucija', common: 'Sveta Lucija' },
      hun: { official: 'Saint Lucia', common: 'Saint Lucia' },
      ita: { official: 'Santa Lucia', common: 'Santa Lucia' },
      jpn: { official: 'セントルシア', common: 'セントルシア' },
      kor: { official: '세인트루시아', common: '세인트루시아' },
      nld: { official: 'Saint Lucia', common: 'Saint Lucia' },
      per: { official: 'سنت لوسیا', common: 'سنت لوسیا' },
      pol: { official: 'Saint Lucia', common: 'Saint Lucia' },
      por: { official: 'Santa Lúcia', common: 'Santa Lúcia' },
      rus: { official: 'Сент-Люсия', common: 'Сент-Люсия' },
      slk: { official: 'Svätá Lucia', common: 'Svätá Lucia' },
      spa: { official: 'Santa Lucía', common: 'Santa Lucía' },
      srp: { official: 'Света Луција', common: 'Света Луција' },
      swe: { official: 'Saint Lucia', common: 'Saint Lucia' },
      tur: { official: 'Saint Lucia', common: 'Saint Lucia' },
      urd: { official: 'سینٹ لوسیا', common: 'سینٹ لوسیا' },
      zho: { official: '圣卢西亚', common: '圣卢西亚' },
    },
    latlng: [13.88333333, -60.96666666],
    landlocked: false,
    area: 616.0,
    demonyms: {
      eng: { f: 'Saint Lucian', m: 'Saint Lucian' },
      fra: { f: 'Saint-Lucienne', m: 'Saint-Lucien' },
    },
    flag: '\uD83C\uDDF1\uD83C\uDDE8',
    maps: {
      googleMaps: 'https://goo.gl/maps/4HhJ2jkPdSL9BPRcA',
      openStreetMaps: 'https://www.openstreetmap.org/relation/550728',
    },
    population: 183629,
    gini: { 2016: 51.2 },
    fifa: 'LCA',
    car: { signs: ['WL'], side: 'left' },
    timezones: ['UTC-04:00'],
    continents: ['North America'],
    flags: {
      png: 'https://flagcdn.com/w320/lc.png',
      svg: 'https://flagcdn.com/lc.svg',
      alt: 'The flag of Saint Lucia has a light blue field, at the center of which are two triangles which share a common base — a small golden-yellow isosceles triangle superimposed on a large white-edged black isosceles triangle.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/lc.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/lc.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [14.0, -61.0] },
  },
  {
    name: {
      common: 'Panama',
      official: 'Republic of Panama',
      nativeName: {
        spa: { official: 'República de Panamá', common: 'Panamá' },
      },
    },
    tld: ['.pa'],
    cca2: 'PA',
    ccn3: '591',
    cca3: 'PAN',
    cioc: 'PAN',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: {
      PAB: { name: 'Panamanian balboa', symbol: 'B/.' },
      USD: { name: 'United States dollar', symbol: '$' },
    },
    idd: { root: '+5', suffixes: ['07'] },
    capital: ['Panama City'],
    altSpellings: ['PA', 'Republic of Panama', 'República de Panamá'],
    region: 'Americas',
    subregion: 'Central America',
    languages: { spa: 'Spanish' },
    translations: {
      ara: { official: 'جمهورية بنما', common: 'بنما' },
      bre: { official: 'Republik Panama', common: 'Panama' },
      ces: { official: 'Panamská republika', common: 'Panama' },
      cym: { official: 'Republic of Panama', common: 'Panama' },
      deu: { official: 'Republik Panama', common: 'Panama' },
      est: { official: 'Panama Vabariik', common: 'Panama' },
      fin: { official: 'Panaman tasavalta', common: 'Panama' },
      fra: { official: 'République du Panama', common: 'Panama' },
      hrv: { official: 'Republika Panama', common: 'Panama' },
      hun: { official: 'Panamai Köztársaság', common: 'Panama' },
      ita: { official: 'Repubblica di Panama', common: 'Panama' },
      jpn: { official: 'パナマ共和国', common: 'パナマ' },
      kor: { official: '파나마 공화국', common: '파나마' },
      nld: { official: 'Republiek Panama', common: 'Panama' },
      per: { official: 'جمهوری پاناما', common: 'پاناما' },
      pol: { official: 'Republika Panamy', common: 'Panama' },
      por: { official: 'República do Panamá', common: 'Panamá' },
      rus: { official: 'Республика Панама', common: 'Панама' },
      slk: { official: 'Panamská republika', common: 'Panama' },
      spa: { official: 'República de Panamá', common: 'Panamá' },
      srp: { official: 'Република Панама', common: 'Панама' },
      swe: { official: 'Republiken Panama', common: 'Panama' },
      tur: { official: 'Panama Cumhuriyeti', common: 'Panama' },
      urd: { official: 'جمہوریہ پاناما', common: 'پاناما' },
      zho: { official: '巴拿马共和国', common: '巴拿马' },
    },
    latlng: [9.0, -80.0],
    landlocked: false,
    borders: ['COL', 'CRI'],
    area: 75417.0,
    demonyms: {
      eng: { f: 'Panamanian', m: 'Panamanian' },
      fra: { f: 'Panaméenne', m: 'Panaméen' },
    },
    flag: '\uD83C\uDDF5\uD83C\uDDE6',
    maps: {
      googleMaps: 'https://goo.gl/maps/sEN7sKqeawa5oPNLA',
      openStreetMaps: 'https://www.openstreetmap.org/relation/287668',
    },
    population: 4314768,
    gini: { 2019: 49.8 },
    fifa: 'PAN',
    car: { signs: ['PA'], side: 'right' },
    timezones: ['UTC-05:00'],
    continents: ['North America'],
    flags: {
      png: 'https://flagcdn.com/w320/pa.png',
      svg: 'https://flagcdn.com/pa.svg',
      alt: 'The flag of Panama is composed of four equal rectangular areas — a white rectangular area with a blue five-pointed star at its center, a red rectangular area, a white rectangular area with a red five-pointed star at its center, and a blue rectangular area — in the upper hoist side, upper fly side, lower fly side and lower hoist side respectively.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/pa.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/pa.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [8.97, -79.53] },
  },
  {
    name: {
      common: 'Timor-Leste',
      official: 'Democratic Republic of Timor-Leste',
      nativeName: {
        por: {
          official: 'República Democrática de Timor-Leste',
          common: 'Timor-Leste',
        },
        tet: {
          official: 'Repúblika Demokrátika Timór-Leste',
          common: 'Timór-Leste',
        },
      },
    },
    tld: ['.tl'],
    cca2: 'TL',
    ccn3: '626',
    cca3: 'TLS',
    cioc: 'TLS',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { USD: { name: 'United States dollar', symbol: '$' } },
    idd: { root: '+6', suffixes: ['70'] },
    capital: ['Dili'],
    altSpellings: [
      'TL',
      'East Timor',
      'Democratic Republic of Timor-Leste',
      'República Democrática de Timor-Leste',
      'Repúblika Demokrátika Timór-Leste',
      "Timór Lorosa'e",
      'Timor Lorosae',
    ],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    languages: { por: 'Portuguese', tet: 'Tetum' },
    translations: {
      ara: {
        official: 'جمهورية تيمور الشرقية الديمقراطية',
        common: 'تيمور الشرقية',
      },
      bre: {
        official: 'Republik demakratel Timor ar Reter',
        common: 'Timor ar Reter',
      },
      ces: {
        official: 'Demokratická republika Východní Timor',
        common: 'Východní Timor',
      },
      cym: {
        official: 'Democratic Republic of Timor-Leste',
        common: 'Timor-Leste',
      },
      deu: {
        official: 'Demokratische Republik Timor-Leste',
        common: 'Osttimor',
      },
      est: {
        official: 'Timor-Leste Demokraatlik Vabariik',
        common: 'Ida-Timor',
      },
      fin: {
        official: 'Itä-Timorin demokraattinen tasavalta',
        common: 'Itä-Timor',
      },
      fra: {
        official: 'République démocratique du Timor oriental',
        common: 'Timor oriental',
      },
      hrv: {
        official: 'Demokratska Republika Timor-Leste',
        common: 'Istočni Timor',
      },
      hun: {
        official: 'Kelet-timori Demokratikus Köztársaság',
        common: 'Kelet-Timor',
      },
      ita: {
        official: 'Repubblica Democratica di Timor Est',
        common: 'Timor Est',
      },
      jpn: { official: '東ティモール民主共和国', common: '東ティモール' },
      kor: { official: '동티모르 민주 공화국', common: '동티모르' },
      nld: {
        official: 'Democratische Republiek Oost-Timor',
        common: 'Oost-Timor',
      },
      per: { official: 'جمهوری دموکراتیک تیمور شرقی', common: 'تیمور شرقی' },
      pol: {
        official: 'Demokratyczna Republika Timoru Wschodniego',
        common: 'Timor Wschodni',
      },
      por: {
        official: 'República Democrática de Timor-Leste',
        common: 'Timor-Leste',
      },
      rus: {
        official: 'Демократическая Республика Тимор -Лешти',
        common: 'Восточный Тимор',
      },
      slk: {
        official: 'Východotimorská demokratická republika',
        common: 'Východný Timor',
      },
      spa: {
        official: 'República Democrática de Timor-Leste',
        common: 'Timor Oriental',
      },
      srp: {
        official: 'Демократска Република Источни Тимор',
        common: 'Источни Тимор',
      },
      swe: { official: 'Demokratiska republiken Östtimor', common: 'Östtimor' },
      tur: {
        official: 'Doğu Timor Demokratik Cumhuriyeti',
        common: 'Doğu Timor',
      },
      urd: { official: 'جمہوری جمہوریہ مشرقی تیمور', common: 'مشرقی تیمور' },
      zho: { official: '东帝汶民主共和国', common: '东帝汶' },
    },
    latlng: [-8.83333333, 125.91666666],
    landlocked: false,
    borders: ['IDN'],
    area: 14874.0,
    demonyms: {
      eng: { f: 'East Timorese', m: 'East Timorese' },
      fra: { f: 'Est-timoraise', m: 'Est-timorais' },
    },
    flag: '\uD83C\uDDF9\uD83C\uDDF1',
    maps: {
      googleMaps: 'https://goo.gl/maps/sFqBC9zjgUXPR1iTA',
      openStreetMaps: 'https://www.openstreetmap.org/relation/305142',
    },
    population: 1318442,
    gini: { 2014: 28.7 },
    fifa: 'TLS',
    car: { signs: ['TL'], side: 'left' },
    timezones: ['UTC+09:00'],
    continents: ['Oceania'],
    flags: {
      png: 'https://flagcdn.com/w320/tl.png',
      svg: 'https://flagcdn.com/tl.svg',
      alt: 'The flag of Timor-Leste has a red field with two isosceles triangles which share a common base on the hoist end. The smaller black triangle, which bears a five-pointed white star at its center and spans one-third the width of the field, is superimposed on the larger yellow triangle that extends to the center of the field.',
    },
    coatOfArms: {},
    startOfWeek: 'monday',
    capitalInfo: { latlng: [-8.58, 125.6] },
  },
  {
    name: {
      common: 'North Macedonia',
      official: 'Republic of North Macedonia',
      nativeName: {
        mkd: { official: 'Република Северна Македонија', common: 'Македонија' },
      },
    },
    tld: ['.mk'],
    cca2: 'MK',
    ccn3: '807',
    cca3: 'MKD',
    cioc: 'MKD',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { MKD: { name: 'denar', symbol: 'den' } },
    idd: { root: '+3', suffixes: ['89'] },
    capital: ['Skopje'],
    altSpellings: [
      'MK',
      'The former Yugoslav Republic of Macedonia',
      'Republic of North Macedonia',
      'Macedonia, The Former Yugoslav Republic of',
      'Република Северна Македонија',
    ],
    region: 'Europe',
    subregion: 'Southeast Europe',
    languages: { mkd: 'Macedonian' },
    translations: {
      ara: { official: 'جمهورية شمال مقدونيا', common: 'شمال مقدونيا' },
      bre: {
        official: 'Republik Makedonia an Norzh',
        common: 'Makedonia an Norzh',
      },
      ces: {
        official: 'Republika Severní Makedonie',
        common: 'Severní Makedonie',
      },
      cym: {
        official: 'Republic of North Macedonia',
        common: 'North Macedonia',
      },
      deu: { official: 'Republik Nordmazedonien', common: 'Nordmazedonien' },
      est: {
        official: 'Põhja-Makedoonia Vabariik',
        common: 'Põhja-Makedoonia',
      },
      fin: {
        official: 'Pohjois-Makedonian tasavalta',
        common: 'Pohjois-Makedonia',
      },
      fra: {
        official: 'République de Macédoine du Nord',
        common: 'Macédoine du Nord',
      },
      hrv: {
        official: 'Republika Sjeverna Makedonija',
        common: 'Sjeverna Makedonija',
      },
      hun: { official: 'Észak-macedón Köztársaság', common: 'Észak-Macedónia' },
      ita: {
        official: 'Repubblica di Macedonia del Nord',
        common: 'Macedonia del Nord',
      },
      jpn: { official: '北マケドニア共和国', common: '北マケドニア ' },
      kor: { official: '북마케도니아 공화국', common: '북마케도니아' },
      nld: { official: 'Republiek Noord-Macedonië', common: 'Noord-Macedonië' },
      per: { official: 'جمهوری مقدونیه شمالی', common: 'مقدونیه شمالی' },
      pol: {
        official: 'Republika Macedonii Północnej',
        common: 'Macedonia Północna',
      },
      por: {
        official: 'República da Macedônia do Norte',
        common: 'Macedónia do Norte',
      },
      rus: {
        official: 'Республика Северная Македония',
        common: 'Северная Македония',
      },
      slk: {
        official: 'Severomacedónska republika',
        common: 'Severné Macedónsko',
      },
      spa: {
        official: 'República de Macedonia del Norte',
        common: 'Macedonia del Norte',
      },
      srp: {
        official: 'Република Северна Македонија',
        common: 'Северна Македонија',
      },
      swe: { official: 'Republiken Nordmakedonien', common: 'Nordmakedonien' },
      tur: {
        official: 'Kuzey Makedonya Cumhuriyeti',
        common: 'Kuzey Makedonya',
      },
      urd: { official: 'جمہوریہ مقدونیہ', common: 'شمالی مقدونیہ' },
      zho: { official: '北馬其頓共和國', common: '北馬其頓' },
    },
    latlng: [41.83333333, 22.0],
    landlocked: true,
    borders: ['ALB', 'BGR', 'GRC', 'UNK', 'SRB'],
    area: 25713.0,
    demonyms: {
      eng: { f: 'Macedonian', m: 'Macedonian' },
      fra: { f: 'Macédonienne', m: 'Macédonien' },
    },
    flag: '\uD83C\uDDF2\uD83C\uDDF0',
    maps: {
      googleMaps: 'https://goo.gl/maps/55Q8MEnF6ACdu3q79',
      openStreetMaps: 'https://www.openstreetmap.org/relation/53293',
    },
    population: 2077132,
    gini: { 2018: 33.0 },
    fifa: 'MKD',
    car: { signs: ['MK'], side: 'right' },
    timezones: ['UTC+01:00'],
    continents: ['Europe'],
    flags: {
      png: 'https://flagcdn.com/w320/mk.png',
      svg: 'https://flagcdn.com/mk.svg',
      alt: 'The flag of North Macedonia has a red field, at the center of which is a golden-yellow sun with eight broadening rays that extend to the edges of the field.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/mk.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/mk.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [42.0, 21.43] },
    postalCode: { format: '####', regex: '^(\\d{4})$' },
  },
  {
    name: {
      common: 'Denmark',
      official: 'Kingdom of Denmark',
      nativeName: {
        dan: { official: 'Kongeriget Danmark', common: 'Danmark' },
      },
    },
    tld: ['.dk'],
    cca2: 'DK',
    ccn3: '208',
    cca3: 'DNK',
    cioc: 'DEN',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { DKK: { name: 'Danish krone', symbol: 'kr' } },
    idd: { root: '+4', suffixes: ['5'] },
    capital: ['Copenhagen'],
    altSpellings: ['DK', 'Danmark', 'Kingdom of Denmark', 'Kongeriget Danmark'],
    region: 'Europe',
    subregion: 'Northern Europe',
    languages: { dan: 'Danish' },
    translations: {
      ara: { official: 'مملكة الدنمارك', common: 'الدنمارك' },
      bre: { official: 'Rouantelezh Danmark', common: 'Danmark' },
      ces: { official: 'Dánské království', common: 'Dánsko' },
      cym: { official: 'Teyrnas Denmarc', common: 'Denmarc' },
      deu: { official: 'Königreich Dänemark', common: 'Dänemark' },
      est: { official: 'Taani Kuningriik', common: 'Taani' },
      fin: { official: 'Tanskan kuningaskunta', common: 'Tanska' },
      fra: { official: 'Royaume du Danemark', common: 'Danemark' },
      hrv: { official: 'Kraljevina Danska', common: 'Danska' },
      hun: { official: 'Dán Királyság', common: 'Dánia' },
      ita: { official: 'Regno di Danimarca', common: 'Danimarca' },
      jpn: { official: 'デンマーク王国', common: 'デンマーク' },
      kor: { official: '덴마크 왕국', common: '덴마크' },
      nld: { official: 'Koninkrijk Denemarken', common: 'Denemarken' },
      per: { official: 'پادشاهی دانمارک', common: 'دانمارک' },
      pol: { official: 'Królestwo Danii', common: 'Dania' },
      por: { official: 'Reino da Dinamarca', common: 'Dinamarca' },
      rus: { official: 'Королевство Дания', common: 'Дания' },
      slk: { official: 'Dánske kráľovstvo', common: 'Dánsko' },
      spa: { official: 'Reino de Dinamarca', common: 'Dinamarca' },
      srp: { official: 'Краљевина Данска', common: 'Данска' },
      swe: { official: 'Konungariket Danmark', common: 'Danmark' },
      tur: { official: 'Danimarka Krallığı', common: 'Danimarka' },
      urd: { official: 'مملکتِ ڈنمارک', common: 'ڈنمارک' },
      zho: { official: '丹麦王国', common: '丹麦' },
    },
    latlng: [56.0, 10.0],
    landlocked: false,
    borders: ['DEU'],
    area: 43094.0,
    demonyms: {
      eng: { f: 'Danish', m: 'Danish' },
      fra: { f: 'Danoise', m: 'Danois' },
    },
    flag: '\uD83C\uDDE9\uD83C\uDDF0',
    maps: {
      googleMaps: 'https://goo.gl/maps/UddGPN7hAyrtpFiT6',
      openStreetMaps: 'https://www.openstreetmap.org/relation/50046',
    },
    population: 5831404,
    gini: { 2018: 28.2 },
    fifa: 'DEN',
    car: { signs: ['DK'], side: 'right' },
    timezones: ['UTC-04:00', 'UTC-03:00', 'UTC-01:00', 'UTC', 'UTC+01:00'],
    continents: ['Europe'],
    flags: {
      png: 'https://flagcdn.com/w320/dk.png',
      svg: 'https://flagcdn.com/dk.svg',
      alt: 'The flag of Denmark has a red field with a large white cross that extend to the edges of the field. The vertical part of this cross is offset towards the hoist side.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/dk.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/dk.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [55.67, 12.58] },
    postalCode: { format: '####', regex: '^(\\d{4})$' },
  },
  {
    name: {
      common: 'Egypt',
      official: 'Arab Republic of Egypt',
      nativeName: { ara: { official: 'جمهورية مصر العربية', common: 'مصر' } },
    },
    tld: ['.eg', '.مصر'],
    cca2: 'EG',
    ccn3: '818',
    cca3: 'EGY',
    cioc: 'EGY',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { EGP: { name: 'Egyptian pound', symbol: '£' } },
    idd: { root: '+2', suffixes: ['0'] },
    capital: ['Cairo'],
    altSpellings: ['EG', 'Arab Republic of Egypt'],
    region: 'Africa',
    subregion: 'Northern Africa',
    languages: { ara: 'Arabic' },
    translations: {
      ara: { official: 'جمهورية مصر العربية', common: 'مصر' },
      bre: { official: 'Republik arab Egipt', common: 'Egipt' },
      ces: { official: 'Egyptská arabská republika', common: 'Egypt' },
      cym: { official: 'Gweriniaeth Arabaidd yr Aifft', common: 'Yr Aifft' },
      deu: { official: 'Arabische Republik Ägypten', common: 'Ägypten' },
      est: { official: 'Egiptuse Araabia Vabariik', common: 'Egiptus' },
      fin: { official: 'Egyptin arabitasavalta', common: 'Egypti' },
      fra: { official: "République arabe d'Égypte", common: 'Égypte' },
      hrv: { official: 'Arapska Republika Egipat', common: 'Egipat' },
      hun: { official: 'Egyiptomi Arab Köztársaság', common: 'Egyiptom' },
      ita: { official: "Repubblica araba d'Egitto", common: 'Egitto' },
      jpn: { official: 'エジプト·アラブ共和国', common: 'エジプト' },
      kor: { official: '이집트 아랍 공화국', common: '이집트' },
      nld: { official: 'Arabische Republiek Egypte', common: 'Egypte' },
      per: { official: 'جمهوری عربی مصر', common: 'مصر' },
      pol: { official: 'Arabska Republika Egiptu', common: 'Egipt' },
      por: { official: 'República Árabe do Egipto', common: 'Egito' },
      rus: { official: 'Арабская Республика Египет', common: 'Египет' },
      slk: { official: 'Egyptská arabská republika', common: 'Egypt' },
      spa: { official: 'República Árabe de Egipto', common: 'Egipto' },
      srp: { official: 'Арапска Република Египат', common: 'Египат' },
      swe: { official: 'Arabrepubliken Egypten', common: 'Egypten' },
      tur: { official: 'Mısır Arap Cumhuriyeti', common: 'Mısır' },
      urd: { official: 'مصری عرب جمہوریہ', common: 'مصر' },
      zho: { official: '阿拉伯埃及共和国', common: '埃及' },
    },
    latlng: [27.0, 30.0],
    landlocked: false,
    borders: ['ISR', 'LBY', 'PSE', 'SDN'],
    area: 1002450.0,
    demonyms: {
      eng: { f: 'Egyptian', m: 'Egyptian' },
      fra: { f: 'Égyptienne', m: 'Égyptien' },
    },
    flag: '\uD83C\uDDEA\uD83C\uDDEC',
    maps: {
      googleMaps: 'https://goo.gl/maps/uoDRhXbsqjG6L7VG7',
      openStreetMaps: 'https://www.openstreetmap.org/relation/1473947',
    },
    population: 102334403,
    gini: { 2017: 31.5 },
    fifa: 'EGY',
    car: { signs: ['ET'], side: 'right' },
    timezones: ['UTC+02:00'],
    continents: ['Africa'],
    flags: {
      png: 'https://flagcdn.com/w320/eg.png',
      svg: 'https://flagcdn.com/eg.svg',
      alt: "The flag of Egypt is composed of three equal horizontal bands of red, white and black, with Egypt's national emblem — a hoist-side facing gold eagle of Saladin — centered in the white band.",
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/eg.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/eg.svg',
    },
    startOfWeek: 'sunday',
    capitalInfo: { latlng: [30.05, 31.25] },
    postalCode: { format: '#####', regex: '^(\\d{5})$' },
  },
  {
    name: {
      common: 'Estonia',
      official: 'Republic of Estonia',
      nativeName: { est: { official: 'Eesti Vabariik', common: 'Eesti' } },
    },
    tld: ['.ee'],
    cca2: 'EE',
    ccn3: '233',
    cca3: 'EST',
    cioc: 'EST',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { EUR: { name: 'Euro', symbol: '€' } },
    idd: { root: '+3', suffixes: ['72'] },
    capital: ['Tallinn'],
    altSpellings: ['EE', 'Eesti', 'Republic of Estonia', 'Eesti Vabariik'],
    region: 'Europe',
    subregion: 'Northern Europe',
    languages: { est: 'Estonian' },
    translations: {
      ara: { official: 'جمهورية إستونيا', common: 'إستونيا' },
      bre: { official: 'Republik Estonia', common: 'Estonia' },
      ces: { official: 'Estonská republika', common: 'Estonsko' },
      cym: { official: 'Gweriniaeth Estonia', common: 'Estonia' },
      deu: { official: 'Republik Estland', common: 'Estland' },
      est: { official: 'Eesti Vabariik', common: 'Eesti' },
      fin: { official: 'Viron tasavalta', common: 'Viro' },
      fra: { official: "République d'Estonie", common: 'Estonie' },
      hrv: { official: 'Republika Estonija', common: 'Estonija' },
      hun: { official: 'Észt Köztársaság', common: 'Észtország' },
      ita: { official: 'Repubblica di Estonia', common: 'Estonia' },
      jpn: { official: 'エストニア共和国', common: 'エストニア' },
      kor: { official: '에스토니아 공화국', common: '에스토니아' },
      nld: { official: 'Republiek Estland', common: 'Estland' },
      per: { official: 'جمهوری استونی', common: 'اِستونی' },
      pol: { official: 'Republika Estońska', common: 'Estonia' },
      por: { official: 'República da Estónia', common: 'Estónia' },
      rus: { official: 'Эстонская Республика', common: 'Эстония' },
      slk: { official: 'Estónska republika', common: 'Estónsko' },
      spa: { official: 'República de Estonia', common: 'Estonia' },
      srp: { official: 'Естонска Република', common: 'Естонија' },
      swe: { official: 'Republiken Estland', common: 'Estland' },
      tur: { official: 'Estonya Cumhuriyeti', common: 'Estonya' },
      urd: { official: 'جمہوریہ اسٹونیا', common: 'اسٹونیا' },
      zho: { official: '爱沙尼亚共和国', common: '爱沙尼亚' },
    },
    latlng: [59.0, 26.0],
    landlocked: false,
    borders: ['LVA', 'RUS'],
    area: 45227.0,
    demonyms: {
      eng: { f: 'Estonian', m: 'Estonian' },
      fra: { f: 'Estonienne', m: 'Estonien' },
    },
    flag: '\uD83C\uDDEA\uD83C\uDDEA',
    maps: {
      googleMaps: 'https://goo.gl/maps/6SsynwGUodL1sDvq8',
      openStreetMaps: 'https://www.openstreetmap.org/relation/79510',
    },
    population: 1331057,
    gini: { 2018: 30.3 },
    fifa: 'EST',
    car: { signs: ['EST'], side: 'right' },
    timezones: ['UTC+02:00'],
    continents: ['Europe'],
    flags: {
      png: 'https://flagcdn.com/w320/ee.png',
      svg: 'https://flagcdn.com/ee.svg',
      alt: 'The flag of Estonia is composed of three equal horizontal bands of blue, black and white.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/ee.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/ee.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [59.43, 24.72] },
    postalCode: { format: '#####', regex: '^(\\d{5})$' },
  },
  {
    name: {
      common: 'Czechia',
      official: 'Czech Republic',
      nativeName: {
        ces: { official: 'Česká republika', common: 'Česko' },
        slk: { official: 'Česká republika', common: 'Česko' },
      },
    },
    tld: ['.cz'],
    cca2: 'CZ',
    ccn3: '203',
    cca3: 'CZE',
    cioc: 'CZE',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { CZK: { name: 'Czech koruna', symbol: 'Kč' } },
    idd: { root: '+4', suffixes: ['20'] },
    capital: ['Prague'],
    altSpellings: ['CZ', 'Česká republika', 'Česko'],
    region: 'Europe',
    subregion: 'Central Europe',
    languages: { ces: 'Czech', slk: 'Slovak' },
    translations: {
      ara: { official: 'جمهورية التشيك', common: 'التشيك' },
      bre: { official: 'Republik Tchek', common: 'Tchekia' },
      ces: { official: 'Česká republika', common: 'Česko' },
      cym: { official: 'Y Weriniaeth Tsiec', common: 'Y Weriniaeth Tsiec' },
      deu: { official: 'Tschechische Republik', common: 'Tschechien' },
      est: { official: 'Tšehhi Vabariik', common: 'Tšehhi' },
      fin: { official: 'Tšekin tasavalta', common: 'Tšekki' },
      fra: { official: 'République tchèque', common: 'Tchéquie' },
      hrv: { official: 'Češka', common: 'Češka' },
      hun: { official: 'Cseh Köztársaság', common: 'Csehország' },
      ita: { official: 'Repubblica Ceca', common: 'Cechia' },
      jpn: { official: 'チェコ共和国', common: 'チェコ' },
      kor: { official: '체코', common: '체코' },
      nld: { official: 'Tsjechische Republiek', common: 'Tsjechië' },
      per: { official: 'جمهوری چک', common: 'جمهوری چک' },
      pol: { official: 'Republika Czeska', common: 'Czechy' },
      por: { official: 'República Checa', common: 'Chéquia' },
      rus: { official: 'Чешская Республика', common: 'Чехия' },
      slk: { official: 'Česká republika', common: 'Česko' },
      spa: { official: 'República Checa', common: 'Chequia' },
      srp: { official: 'Чешка Република', common: 'Чешка' },
      swe: { official: 'Republiken Tjeckien', common: 'Tjeckien' },
      tur: { official: 'Çek Cumhuriyeti', common: 'Çekya' },
      urd: { official: 'چيک جمہوريہ', common: 'چيک' },
      zho: { official: '捷克共和国', common: '捷克' },
    },
    latlng: [49.75, 15.5],
    landlocked: true,
    borders: ['AUT', 'DEU', 'POL', 'SVK'],
    area: 78865.0,
    demonyms: {
      eng: { f: 'Czech', m: 'Czech' },
      fra: { f: 'Tchèque', m: 'Tchèque' },
    },
    flag: '\uD83C\uDDE8\uD83C\uDDFF',
    maps: {
      googleMaps: 'https://goo.gl/maps/47dmgeXMZyhDHyQW8',
      openStreetMaps: 'https://www.openstreetmap.org/relation/51684',
    },
    population: 10698896,
    gini: { 2018: 25.0 },
    fifa: 'CZE',
    car: { signs: ['CZ'], side: 'right' },
    timezones: ['UTC+01:00'],
    continents: ['Europe'],
    flags: {
      png: 'https://flagcdn.com/w320/cz.png',
      svg: 'https://flagcdn.com/cz.svg',
      alt: 'The flag of Czechia is composed of two equal horizontal bands of white and red, with a blue isosceles triangle superimposed on the hoist side of the field. The triangle has its base on the hoist end and spans about two-fifth the width of the field.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/cz.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/cz.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [50.08, 14.47] },
    postalCode: { format: '### ##', regex: '^(\\d{5})$' },
  },
  {
    name: {
      common: 'Bahamas',
      official: 'Commonwealth of the Bahamas',
      nativeName: {
        eng: { official: 'Commonwealth of the Bahamas', common: 'Bahamas' },
      },
    },
    tld: ['.bs'],
    cca2: 'BS',
    ccn3: '044',
    cca3: 'BHS',
    cioc: 'BAH',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: {
      BSD: { name: 'Bahamian dollar', symbol: '$' },
      USD: { name: 'United States dollar', symbol: '$' },
    },
    idd: { root: '+1', suffixes: ['242'] },
    capital: ['Nassau'],
    altSpellings: ['BS', 'Commonwealth of the Bahamas'],
    region: 'Americas',
    subregion: 'Caribbean',
    languages: { eng: 'English' },
    translations: {
      ara: { official: 'كومنولث جزر البهاما', common: 'باهاماس' },
      bre: { official: 'Kenglad ar Bahamas', common: 'Bahamas' },
      ces: { official: 'Bahamské společenství', common: 'Bahamy' },
      cym: { official: 'Cymanwlad y Bahamas', common: 'Bahamas' },
      deu: { official: 'Commonwealth der Bahamas', common: 'Bahamas' },
      est: { official: 'Bahama Ühendus', common: 'Bahama' },
      fin: { official: 'Bahaman liittovaltio', common: 'Bahamasaaret' },
      fra: { official: 'Commonwealth des Bahamas', common: 'Bahamas' },
      hrv: { official: 'Zajednica Bahama', common: 'Bahami' },
      hun: { official: 'Bahamai Közösség', common: 'Bahama-szigetek' },
      ita: { official: 'Commonwealth delle Bahamas', common: 'Bahamas' },
      jpn: { official: 'バハマ', common: 'バハマ' },
      kor: { official: '바하마 연방', common: '바하마' },
      nld: { official: "Gemenebest van de Bahama's", common: 'Bahama’s' },
      per: { official: 'قلمرو همسود باهاما', common: 'باهاما' },
      pol: { official: 'Bahamy', common: 'Bahamy' },
      por: { official: 'Comunidade das Bahamas', common: 'Bahamas' },
      rus: {
        official: 'Содружество Багамских Островов',
        common: 'Багамские Острова',
      },
      slk: { official: 'Bahamské spoločenstvo', common: 'Bahamy' },
      spa: { official: 'Commonwealth de las Bahamas', common: 'Bahamas' },
      srp: { official: 'Комонвелт Бахама', common: 'Бахами' },
      swe: { official: 'Samväldet Bahamas', common: 'Bahamas' },
      tur: { official: 'Bahama Milletler Topluluğu', common: 'Bahamalar' },
      urd: { official: 'دولتِ مشترکہ بہاماس', common: 'بہاماس' },
      zho: { official: '巴哈马联邦', common: '巴哈马' },
    },
    latlng: [25.0343, 77.3963],
    landlocked: false,
    area: 13943.0,
    demonyms: {
      eng: { f: 'Bahamian', m: 'Bahamian' },
      fra: { f: 'Bahamienne', m: 'Bahamien' },
    },
    flag: '\uD83C\uDDE7\uD83C\uDDF8',
    maps: {
      googleMaps: 'https://goo.gl/maps/1YzRs1BZrG8p8pmVA',
      openStreetMaps: 'https://www.openstreetmap.org/relation/547469',
    },
    population: 393248,
    fifa: 'BAH',
    car: { signs: ['BS'], side: 'left' },
    timezones: ['UTC-05:00'],
    continents: ['North America'],
    flags: {
      png: 'https://flagcdn.com/w320/bs.png',
      svg: 'https://flagcdn.com/bs.svg',
      alt: 'The flag of the Bahamas is composed of three equal horizontal bands of aquamarine, yellow and aquamarine, with a black equilateral triangle superimposed on the hoist side of the field. This triangle has its base on the hoist end and spans about one-third the width of the field.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/bs.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/bs.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [25.08, -77.35] },
  },
  {
    name: {
      common: 'Uruguay',
      official: 'Oriental Republic of Uruguay',
      nativeName: {
        spa: { official: 'República Oriental del Uruguay', common: 'Uruguay' },
      },
    },
    tld: ['.uy'],
    cca2: 'UY',
    ccn3: '858',
    cca3: 'URY',
    cioc: 'URU',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { UYU: { name: 'Uruguayan peso', symbol: '$' } },
    idd: { root: '+5', suffixes: ['98'] },
    capital: ['Montevideo'],
    altSpellings: [
      'UY',
      'Oriental Republic of Uruguay',
      'República Oriental del Uruguay',
    ],
    region: 'Americas',
    subregion: 'South America',
    languages: { spa: 'Spanish' },
    translations: {
      ara: { official: 'جمهورية الأوروغواي الشرقية', common: 'الأوروغواي' },
      bre: { official: 'Republik Reter Uruguay', common: 'Uruguay' },
      ces: { official: 'Uruguayská východní republika', common: 'Uruguay' },
      cym: { official: 'Oriental Republic of Uruguay', common: 'Uruguay' },
      deu: { official: 'Republik Östlich des Uruguay', common: 'Uruguay' },
      est: { official: 'Uruguay Idavabariik', common: 'Uruguay' },
      fin: { official: 'Uruguayn itäinen tasavalta', common: 'Uruguay' },
      fra: { official: "République orientale de l'Uruguay", common: 'Uruguay' },
      hrv: { official: 'Orijentalna Republika Urugvaj', common: 'Urugvaj' },
      hun: { official: 'Uruguayi Keleti Köztársaság', common: 'Uruguay' },
      ita: { official: "Repubblica Orientale dell'Uruguay", common: 'Uruguay' },
      jpn: { official: 'ウルグアイ東方共和国', common: 'ウルグアイ' },
      kor: { official: '우루과이 동방 공화국', common: '우루과이' },
      nld: { official: 'Oosterse Republiek Uruguay', common: 'Uruguay' },
      per: { official: 'جمهوری اروگوئه', common: 'اروگوئه' },
      pol: { official: 'Wschodnia Republika Urugwaju', common: 'Urugwaj' },
      por: { official: 'República Oriental do Uruguai', common: 'Uruguai' },
      rus: { official: 'Восточной Республики Уругвай', common: 'Уругвай' },
      slk: { official: 'Uruguajská východná republika', common: 'Uruguaj' },
      spa: { official: 'República Oriental del Uruguay', common: 'Uruguay' },
      srp: { official: 'Источна Република Уругвај', common: 'Уругвај' },
      swe: { official: 'Republiken Uruguay', common: 'Uruguay' },
      tur: { official: 'Uruguay Doğu Cumhuriyeti', common: 'Uruguay' },
      urd: { official: 'جمہوریہ شرقیہ یوراگوئے', common: 'یوراگوئے' },
      zho: { official: '乌拉圭东岸共和国', common: '乌拉圭' },
    },
    latlng: [-33.0, -56.0],
    landlocked: false,
    borders: ['ARG', 'BRA'],
    area: 181034.0,
    demonyms: {
      eng: { f: 'Uruguayan', m: 'Uruguayan' },
      fra: { f: 'Uruguayenne', m: 'Uruguayen' },
    },
    flag: '\uD83C\uDDFA\uD83C\uDDFE',
    maps: {
      googleMaps: 'https://goo.gl/maps/tiQ9Baekb1jQtDSD9',
      openStreetMaps: 'https://www.openstreetmap.org/relation/287072',
    },
    population: 3473727,
    gini: { 2019: 39.7 },
    fifa: 'URU',
    car: { signs: ['ROU'], side: 'right' },
    timezones: ['UTC-03:00'],
    continents: ['South America'],
    flags: {
      png: 'https://flagcdn.com/w320/uy.png',
      svg: 'https://flagcdn.com/uy.svg',
      alt: "The flag of Uruguay is composed of nine equal horizontal bands of white alternating with blue, with a white square superimposed in the canton. In the white square is a yellow sun bearing a human face — the Sun of May — from which sixteen rays extend. The sun's rays alternate between triangular and wavy.",
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/uy.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/uy.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [-34.85, -56.17] },
    postalCode: { format: '#####', regex: '^(\\d{5})$' },
  },
  {
    name: {
      common: 'Åland Islands',
      official: 'Åland Islands',
      nativeName: { swe: { official: 'Landskapet Åland', common: 'Åland' } },
    },
    tld: ['.ax'],
    cca2: 'AX',
    ccn3: '248',
    cca3: 'ALA',
    independent: false,
    status: 'officially-assigned',
    unMember: false,
    currencies: { EUR: { name: 'Euro', symbol: '€' } },
    idd: { root: '+3', suffixes: ['5818'] },
    capital: ['Mariehamn'],
    altSpellings: ['AX', 'Aaland', 'Aland', 'Ahvenanmaa'],
    region: 'Europe',
    subregion: 'Northern Europe',
    languages: { swe: 'Swedish' },
    translations: {
      ara: { official: 'جزر أولاند', common: 'جزر أولاند' },
      bre: { official: 'Inizi Åland', common: 'Åland' },
      ces: { official: 'Ålandské ostrovy', common: 'Ålandy' },
      cym: { official: 'Åland Islands', common: 'Åland Islands' },
      deu: { official: 'Åland-Inseln', common: 'Åland' },
      est: { official: 'Ahvenamaa maakond', common: 'Ahvenamaa' },
      fin: { official: 'Ahvenanmaan maakunta', common: 'Ahvenanmaa' },
      fra: { official: 'Ahvenanmaa', common: 'Ahvenanmaa' },
      hrv: { official: 'Aland Islands', common: 'Ålandski otoci' },
      hun: { official: 'Åland-szigetek', common: 'Åland-szigetek' },
      ita: { official: 'Isole Åland', common: 'Isole Aland' },
      jpn: { official: 'オーランド諸島', common: 'オーランド諸島' },
      kor: { official: '올란드 제도', common: '올란드 제도' },
      nld: { official: 'Åland eilanden', common: 'Ålandeilanden' },
      per: { official: 'جزایر الند', common: 'جزایر الند' },
      pol: { official: 'Wyspy Alandzkie', common: 'Wyspy Alandzkie' },
      por: { official: 'Ilhas Åland', common: 'Alândia' },
      rus: { official: 'Аландские острова', common: 'Аландские острова' },
      slk: { official: 'Alandské ostrovy', common: 'Alandy' },
      spa: { official: 'Islas Åland', common: 'Alandia' },
      srp: { official: 'Оландска Острва', common: 'Оландска Острва' },
      swe: { official: 'Åland', common: 'Åland' },
      tur: { official: 'Åland Adaları', common: 'Åland' },
      urd: { official: 'جزائر اولند', common: 'جزائر اولند' },
      zho: { official: '奥兰群岛', common: '奥兰群岛' },
    },
    latlng: [60.116667, 19.9],
    landlocked: false,
    area: 1580.0,
    demonyms: {
      eng: { f: 'Ålandish', m: 'Ålandish' },
      fra: { f: 'Ålandaise', m: 'Ålandais' },
    },
    flag: '\uD83C\uDDE6\uD83C\uDDFD',
    maps: {
      googleMaps: 'https://goo.gl/maps/ewFb3vYsfUmVCoSb8',
      openStreetMaps: 'https://www.openstreetmap.org/relation/1650407',
    },
    population: 29458,
    car: { signs: [''], side: 'right' },
    timezones: ['UTC+02:00'],
    continents: ['Europe'],
    flags: {
      png: 'https://flagcdn.com/w320/ax.png',
      svg: 'https://flagcdn.com/ax.svg',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/ax.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/ax.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [60.12, 19.9] },
  },
  {
    name: {
      common: 'Comoros',
      official: 'Union of the Comoros',
      nativeName: {
        ara: { official: 'الاتحاد القمري', common: 'القمر‎' },
        fra: { official: 'Union des Comores', common: 'Comores' },
        zdj: { official: 'Udzima wa Komori', common: 'Komori' },
      },
    },
    tld: ['.km'],
    cca2: 'KM',
    ccn3: '174',
    cca3: 'COM',
    cioc: 'COM',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { KMF: { name: 'Comorian franc', symbol: 'Fr' } },
    idd: { root: '+2', suffixes: ['69'] },
    capital: ['Moroni'],
    altSpellings: [
      'KM',
      'Union of the Comoros',
      'Union des Comores',
      'Udzima wa Komori',
      'al-Ittiḥād al-Qumurī',
    ],
    region: 'Africa',
    subregion: 'Eastern Africa',
    languages: { ara: 'Arabic', fra: 'French', zdj: 'Comorian' },
    translations: {
      ara: { official: 'الإتحاد القمري', common: 'جزر القمر' },
      bre: { official: 'Unaniezh Komorez', common: 'Komorez' },
      ces: { official: 'Komorský svaz', common: 'Komory' },
      cym: { official: 'Undeb y Comoros', common: 'Y Comoros' },
      deu: { official: 'Union der Komoren', common: 'Komoren' },
      est: { official: 'Komoori Liit', common: 'Komoorid' },
      fin: { official: 'Komorien liitto', common: 'Komorit' },
      fra: { official: 'Union des Comores', common: 'Comores' },
      hrv: { official: 'Savez Komori', common: 'Komori' },
      hun: { official: 'Comore-szigeteki Unió', common: 'Comore-szigetek' },
      ita: { official: 'Unione delle Comore', common: 'Comore' },
      jpn: { official: 'コモロ連合', common: 'コモロ' },
      kor: { official: '코모로 연방', common: '코모로' },
      nld: { official: 'Unie van de Comoren', common: 'Comoren' },
      per: { official: 'مجمع‌الجزایر قمر', common: 'اتحاد قُمُر' },
      pol: { official: 'Związek Komorów', common: 'Komory' },
      por: { official: 'União das Comores', common: 'Comores' },
      rus: { official: 'Союз Коморских Островов', common: 'Коморы' },
      slk: { official: 'Komorská únia', common: 'Komory' },
      spa: { official: 'Unión de las Comoras', common: 'Comoras' },
      srp: { official: 'Савез Комора', common: 'Комори' },
      swe: { official: 'Unionen Komorerna', common: 'Komorerna' },
      tur: { official: 'Komorlar Birliği', common: 'Komorlar' },
      urd: { official: 'اتحاد القمری', common: 'القمری' },
      zho: { official: '科摩罗联盟', common: '科摩罗' },
    },
    latlng: [-12.16666666, 44.25],
    landlocked: false,
    area: 1862.0,
    demonyms: {
      eng: { f: 'Comoran', m: 'Comoran' },
      fra: { f: 'Comorienne', m: 'Comorien' },
    },
    flag: '\uD83C\uDDF0\uD83C\uDDF2',
    maps: {
      googleMaps: 'https://goo.gl/maps/eas4GP28C1GyStnu6',
      openStreetMaps: 'https://www.openstreetmap.org/relation/535790',
    },
    population: 869595,
    gini: { 2014: 45.3 },
    fifa: 'COM',
    car: { signs: ['COM'], side: 'right' },
    timezones: ['UTC+03:00'],
    continents: ['Africa'],
    flags: {
      png: 'https://flagcdn.com/w320/km.png',
      svg: 'https://flagcdn.com/km.svg',
      alt: 'The flag of Comoros is composed of four equal horizontal bands of yellow, white, red and blue, with a green isosceles triangle superimposed on the hoist side of the field. This triangle has its base on the hoist end, spans about two-fifth the width of the field and bears a fly-side facing white crescent and four five-pointed white stars arranged in a vertical line along the opening of the crescent.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/km.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/km.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [-11.7, 43.23] },
  },
  {
    name: {
      common: 'Cook Islands',
      official: 'Cook Islands',
      nativeName: {
        eng: { official: 'Cook Islands', common: 'Cook Islands' },
        rar: { official: "Kūki 'Āirani", common: "Kūki 'Āirani" },
      },
    },
    tld: ['.ck'],
    cca2: 'CK',
    ccn3: '184',
    cca3: 'COK',
    cioc: 'COK',
    independent: false,
    status: 'officially-assigned',
    unMember: false,
    currencies: {
      CKD: { name: 'Cook Islands dollar', symbol: '$' },
      NZD: { name: 'New Zealand dollar', symbol: '$' },
    },
    idd: { root: '+6', suffixes: ['82'] },
    capital: ['Avarua'],
    altSpellings: ['CK', "Kūki 'Āirani"],
    region: 'Oceania',
    subregion: 'Polynesia',
    languages: { eng: 'English', rar: 'Cook Islands Māori' },
    translations: {
      ara: { official: 'جزر كوك', common: 'جزر كوك' },
      bre: { official: 'Inizi Cook', common: 'Inizi Cook' },
      ces: { official: 'Cookovy ostrovy', common: 'Cookovy ostrovy' },
      cym: { official: 'Ynysoedd Cook', common: 'Ynysoedd Cook' },
      deu: { official: 'Cookinseln', common: 'Cookinseln' },
      est: { official: 'Cooki saared', common: 'Cooki saared' },
      fin: { official: 'Cookinsaaret', common: 'Cookinsaaret' },
      fra: { official: 'Îles Cook', common: 'Îles Cook' },
      hrv: { official: 'Cook Islands', common: 'Cookovo Otočje' },
      hun: { official: 'Cook-szigetek', common: 'Cook-szigetek' },
      ita: { official: 'Isole Cook', common: 'Isole Cook' },
      jpn: { official: 'クック諸島', common: 'クック諸島' },
      kor: { official: '쿡 제도', common: '쿡 제도' },
      nld: { official: 'Cook eilanden', common: 'Cookeilanden' },
      per: { official: 'جزایر کوک', common: 'جزایر کوک' },
      pol: { official: 'Wyspy Cooka', common: 'Wyspy Cooka' },
      por: { official: 'Ilhas Cook', common: 'Ilhas Cook' },
      rus: { official: 'острова Кука', common: 'Острова Кука' },
      slk: { official: 'Cookove ostrovy', common: 'Cookove ostrovy' },
      spa: { official: 'Islas Cook', common: 'Islas Cook' },
      srp: { official: 'Кукова Острва', common: 'Кукова Острва' },
      swe: { official: 'Cooköarna', common: 'Cooköarna' },
      tur: { official: 'Cook Adaları', common: 'Cook Adaları' },
      urd: { official: 'جزائر کک', common: 'جزائر کک' },
      zho: { official: '库克群岛', common: '库克群岛' },
    },
    latlng: [-21.23333333, -159.76666666],
    landlocked: false,
    area: 236.0,
    demonyms: {
      eng: { f: 'Cook Islander', m: 'Cook Islander' },
      fra: { f: 'Cookienne', m: 'Cookien' },
    },
    flag: '\uD83C\uDDE8\uD83C\uDDF0',
    maps: {
      googleMaps: 'https://goo.gl/maps/nrGZrvWRGB4WHgDC9',
      openStreetMaps: 'https://www.openstreetmap.org/relation/2184233',
    },
    population: 18100,
    fifa: 'COK',
    car: { signs: ['NZ'], side: 'left' },
    timezones: ['UTC-10:00'],
    continents: ['Oceania'],
    flags: {
      png: 'https://flagcdn.com/w320/ck.png',
      svg: 'https://flagcdn.com/ck.svg',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/ck.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/ck.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [-21.2, -159.77] },
  },
]